### PR TITLE
Categories and Tags for Scenarios

### PR DESCRIPTION
**Pull request by jggoebel**
Backend functionality for https://github.com/hobbyfarm/gargantua/pull/89

Categories and tags can be updated in the admin-ui

Also fixes https://github.com/hobbyfarm/hobbyfarm/issues/162

### CODE REVIEW

**Comment by ebauman** [comment]
rebase for ci/cd i'd imagine

**Comment by ebauman** [comment]
can we add a preview to the dynamic scenarios tab that shows which scenarios currently match? 
that way the admin doesn't have to spin up a new course to see what matches

just a simple list should suffice

**Comment by jggoebel** [comment]
I will add this feature next week!

**Comment by jggoebel** [comment]
@ebauman i have added a list that displays all dynamic added scenarios.

**Comment by jggoebel** [comment]
Fixes [#162](https://github.com/hobbyfarm/hobbyfarm/issues/162)

**Comment by ebauman** [comment]
Great @jggoebel I will examine

**Pull request merged**
